sudo: true

language: bash

env:
  - PATH=${PATH}:${HOME}/kcov/bin

addons:
  apt:
    packages:
      - binutils-dev
      - libcurl4-openssl-dev
      - libdw-dev
      - libiberty-dev

before_install:
  - ./scripts/print-info.sh
  - ./scripts/download-kcov.sh ./temp/kcov 36
  - ./scripts/build-kcov.sh ./temp/kcov 36

install:
  - ./scripts/install-kcov.sh ./temp/kcov

script:
  - kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern="other,scripts,source/nf,source/ufw,tests" "./temp/kcov/coverage" "./scripts/run-tests.sh"

after_success:
  - bash <(curl -s https://codecov.io/bash) -s ./temp/kcov/coverage
